### ISSUE TITLE
Cannot assign NULL to *time.Time

### ISSUE THREAD

**Issue by sxwebdev** [vgarvardt/pgx-helpers#11]
Hey. Thanks for the great helper for pgx. I have a question

My struct looks like this

```go
type Performance struct {
	Name             string     `json:"name,omitempty" db:"name"`
	Description      string     `json:"description,omitempty" db:"description"`
	StartTime        *time.Time `json:"start_time,omitempty" db:"start_time"`
	EndTime          *time.Time `json:"end_time,omitempty" db:"end_time"`
	Duration         string     `json:"duration,omitempty" db:"duration"`
	EventID          uuid.UUID  `json:"event_id,omitempty" db:"event_id"`
}
```

When I try to scan rows from a database, I get an error

``` cannot assign NULL to *time.Time```

How to resolve this? thx

full code

```go
rows, err := r.store.db.Query(
	context.Background(),
	sql,
	args...,
)
if err != nil {
	return nil, err
}
defer rows.Close()

var items []*model.Performance
err = pgxHelpers.ScanStructs(rows, func() interface{} {
	return new(model.Performance)
}, func(r interface{}) {
	items = append(items, r.(*model.Performance))
})
if err != nil {
	return nil, err
}
```

**Comment by vgarvardt** [comment]
DB drivers in go are working with fields not as with base types. Here is what happens with your model:
- db driver retrieves binary data from DB
- helper provides struct fields as pointers to a driver so it could assign values (convert binary db data to go types)
- db driver checks the type of each field and for primitive types (int, bool, etc.) converts values internally, but for complex types looks for interface methods that are converting binary db data to go type

Taking in consideration short description above here is what happens with `*time.Time` fields - driver tries to assign empty value to a type that does not support `nil` values (time.Time is a complex struct type). The fact that you are using pointer to a type does not help in this case - driver creates instance of the given type first.

To work with nullable db columns there are special types in go. If we're talking about pgx driver - https://github.com/jackc/pgtype would be the best choice as it is from the same author. In your case - `pgtype.Date` or `pgtype.Timestamptz` would be the easiest start. These types encapsulate `time.Time` type and have `Status` field that indicates if the value is `NULL` or not. These types support JSON operations as well, so you can use it for your model w/out significant changes.

**Comment by themafole** [comment]
Thanks for your help, @vgarvardt
